[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ragone"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pybamm",
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ragone*"]

[tool.ruff]
line-length = 88
